### PR TITLE
Add DeviceConfig nodeselector validation

### PR DESCRIPTION
**Pull request by mresvanis**
This PR adds the following changes:

- the addition of a validation during the `DeviceConfig` reconciliation, which checks whether there are any existing `DeviceConfig` CRs in the cluster with conflicting `NodeSelector`s. The latter means that every `DeviceConfig` should target a unique node group, as we cannot have multiple driver versions or configurations in one node.
- the publication of [kubernetes events](https://kubernetes.io/blog/2018/01/reporting-errors-using-kubernetes-events/) for the creation and failed validation of a `DeviceConfig` CR

### CODE REVIEW

**Comment by mresvanis** [comment]
I started coding with the plan of introducing of the `DeviceConfigPool` CRD. But then I thought about the major advantage of having a many-to-many relationship between `DeviceConfigPool`s and `DeviceConfig`s, which is to have multiple `DeviceConfig`s being used by multiple `DeviceConfigPool`s. This makes sense for `MachineConfigPool`s and `MachineConfig`s, because you can actually use multiple `MachineConfig`s in one or more `MachineConfigPool`s. 

In our case, there is a one-to-many relationship, we can only have one `DeviceConfig` per `DeviceConfigPool`. The latter is covered by the `NodeSelector` field of the `DeviceConfig` CRD, as long as there is a simple validation (as the one implemented in this PR). 

The only reason I opted (at this time) to not go with the `DeviceConfigPool` CRD implementation, because I thought that is a bit misleading, as one would think that there is a many-to-many relationship between these `DeviceConfigPool` and `DeviceConfig`.

I could very fast refactor this PR to reflect the `DeviceConfigPool` implementation. So if you think that having a `DeviceConfigPool` (with the respective validation of each CRs, that verify uniqueness of DeviceConfig per Node) is as clear (or even clearer) than the `NodeSelector` field in the `DeviceConfig`, then I'm all up for it.

**Comment by fabiendupont** [comment]
For MachineConfig{,Pool}, the MachineConfigs are merged at runtime by the Render controller, allowing for scoped MachineConfigs that are easier to maintain. So, in the end, the MachineConfigSelector with the Render controller makes it a 1 to many relationship between the rendered config and the node selector.

Ref: [OpenShift Container Platform 4: How does Machine Config Pool work?](https://www.redhat.com/en/blog/openshift-container-platform-4-how-does-machine-config-pool-work)

**Comment by mresvanis** [comment]
Thanks for the blogpost, it's a useful one to have as a reference. I have to insist on the many-to-many though, for example let's look at the specific code: https://github.com/openshift/machine-config-operator/blob/master/pkg/apis/machineconfiguration.openshift.io/v1/types.go#L235

For us this won't be a selector, as we will never have multiple DeviceConfigs used by a single DeviceConfigPool. But maybe I'm missing some other reason that this would be useful in our case (?)

> Absolutely no problem about going this way and development wise it's (almost) exactly the same, although the UX is quite different.

PS. Most of this code, i.e. the validation, is going to be the same :)

**Comment by fabiendupont** [comment]
Let's have a follow-up discussion. This PR looks good with the current implementation.

**Pull request merged**
